=== miraTR24/archiLlgiciel/xml/ToDoList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definition des types complexes -->
  <xs:complexType name="simpleTaskType">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="deadline" type="xs:date"/>
      <xs:element name="priorite">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="HAUTE"/>
            <xs:enumeration value="MOYENNE"/>
            <xs:enumeration value="BASSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="estimatedDuration" type="xs:int"/>
      <xs:element name="progress" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="booleanTaskType">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="deadline" type="xs:date"/>
      <xs:element name="priorite">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="HAUTE"/>
            <xs:enumeration value="MOYENNE"/>
            <xs:enumeration value="BASSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="isCompleted" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="complexTaskType">
    <xs:sequence>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="deadline" type="xs:date"/>
      <xs:element name="priorite">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="HAUTE"/>
            <xs:enumeration value="MOYENNE"/>
            <xs:enumeration value="BASSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="progress" type="xs:int"/> <!-- Barre de progression globale -->
      <xs:element name="subTasks" type="subTasksType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="subTasksType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="simpleTask"/>
        <xs:element ref="booleanTask"/>
        <xs:element ref="complexTask"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <!-- Definition des elements racine -->
  <xs:element name="todoList">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="simpleTask"/>
        <xs:element ref="booleanTask"/>
        <xs:element ref="complexTask"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <!-- Definition des elements -->
  <xs:element name="simpleTask" type="simpleTaskType"/>
  <xs:element name="booleanTask" type="booleanTaskType"/>
  <xs:element name="complexTask" type="complexTaskType"/>

</xs:schema>

=== miraTR24/archiLlgiciel/xml/ToDoList222.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><todoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ToDoList.xsd"><simpleTask><description>hahahah</description><deadline>2024-04-27</deadline><priorite>MOYENNE</priorite><estimatedDuration>1</estimatedDuration><progress>50</progress></simpleTask><simpleTask><description>Nettoyer la maison</description><deadline>2024-04-28</deadline><priorite>BASSE</priorite><estimatedDuration>2</estimatedDuration><progress>20</progress></simpleTask><booleanTask><description>Tondre la pelouse</description><deadline>2024-04-29</deadline><priorite>MOYENNE</priorite><estimatedDuration>2</estimatedDuration><isCompleted>false</isCompleted></booleanTask><complexTask><description>Organiser un dîner</description><deadline>2024-05-02</deadline><priorite>HAUTE</priorite><estimatedDuration>2</estimatedDuration><progress>20</progress><subTasks><simpleTask><description>Préparer le dîner</description><deadline>2024-05-02</deadline><priorite>BASSE</priorite><estimatedDuration>1</estimatedDuration><progress>30</progress></simpleTask><simpleTask><description>Servir le dîner</description><deadline>2024-04-29</deadline><priorite>HAUTE</priorite><estimatedDuration>1</estimatedDuration><progress>10</progress></simpleTask></subTasks></complexTask></todoList>

=== miraTR24/archiLlgiciel/xml/ToDoList.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ToDoList.xsd">
<simpleTask>
        <description>Faire les courses</description>
        <deadline>2024-04-23</deadline>
        <priorite>HAUTE</priorite>
        <estimatedDuration>30</estimatedDuration>
        <progress>10</progress>
    </simpleTask>
    <booleanTask>
        <description>Répondre aux e-mails</description>
        <deadline>2024-04-24</deadline>
        <priorite>MOYENNE</priorite>
        <isCompleted>false</isCompleted>
    </booleanTask>
    <complexTask>
        <description>Organiser un dîner</description>
        <deadline>2024-04-25</deadline>
        <priorite>BASSE</priorite>
        <progress>25</progress> <!-- Barre de progression globale -->
        <subTasks>
            <simpleTask>
                <description>Acheter des ingrédients</description>
                <deadline>2024-04-24</deadline>
                <priorite>MOYENNE</priorite>
                <estimatedDuration>60</estimatedDuration>
                <progress>20</progress>
            </simpleTask>
            <simpleTask>
                <description>Préparer le dîner</description>
                <deadline>2024-04-25</deadline>
                <priorite>HAUTE</priorite>
                <estimatedDuration>120</estimatedDuration>
                <progress>30</progress>
            </simpleTask>
            <booleanTask>
                <description>Inviter des amis</description>
                <deadline>2024-04-26</deadline>
                <priorite>BASSE</priorite>
                <isCompleted>false</isCompleted>
            </booleanTask>
        </subTasks>
    </complexTask>
</todoList>

=== miraTR24/archiLlgiciel/xml/todoList2.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ToDoList.xsd">
 <simpleTask>
    <description>Simple Task 1</description>
    <deadline>2023-03-01</deadline>
    <priorite>HAUTE</priorite>
    <estimatedDuration>5</estimatedDuration>
    <progress>2</progress>
  </simpleTask>
  <booleanTask>
    <description>Boolean Task 1</description>
    <deadline>2023-03-02</deadline>
    <priorite>MOYENNE</priorite>
    <estimatedDuration>10</estimatedDuration>
    <isCompleted>true</isCompleted>
  </booleanTask>
  <complexTask>
    <description>Complex Task 1</description>
    <deadline>2023-03-03</deadline>
    <priorite>BASSE</priorite>
    <subTasks>
      <simpleTask>
        <description>Sub Task 1.1</description>
        <deadline>2023-03-04</deadline>
        <priorite>HAUTE</priorite>
        <estimatedDuration>3</estimatedDuration>
        <progress>1</progress>
      </simpleTask>
      <booleanTask>
        <description>Sub Task 1.2</description>
        <deadline>2023-03-05</deadline>
        <priorite>MOYENNE</priorite>
        <estimatedDuration>2</estimatedDuration>
        <isCompleted>false</isCompleted>
      </booleanTask>
    </subTasks>
    <progress>4</progress>
    <estimatedDuration>10</estimatedDuration>
  </complexTask>
</todoList>
